In [1]:
import numpy as np
lst = [20, 23, 342, 21, -459, -321]
arr = np.array(lst)
print("List: ",lst)
print("Array: ",arr)

List:  [20, 23, 342, 21, -459, -321]
Array:  [  20   23  342   21 -459 -321]


In [4]:
# slice array
arr[2:5]

array([ 342,   21, -459])

In [5]:
b = arr[2:5]

In [6]:
b[0]

342

In [7]:
arr[0]

20

In [8]:
b[:]= 111

In [9]:
b

array([111, 111, 111])

In [10]:
arr

array([  20,   23,  111,  111,  111, -321])

In [11]:
# when we slice an array we dont save the slice
# we can either assign an sliced array to a new array or we can .copy the array and then manipulate data

In [12]:
c = arr.copy()

In [13]:
c

array([  20,   23,  111,  111,  111, -321])

In [14]:
# and then manipulate data to be careful with your given data